// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/grant.proto

package grant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrantService_CreateGrant_FullMethodName = "/grant.GrantService/CreateGrant"
)

// GrantServiceClient is the client API for GrantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrantServiceClient interface {
	CreateGrant(ctx context.Context, in *GrantRequest, opts ...grpc.CallOption) (*GrantResponse, error)
}

type grantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrantServiceClient(cc grpc.ClientConnInterface) GrantServiceClient {
	return &grantServiceClient{cc}
}

func (c *grantServiceClient) CreateGrant(ctx context.Context, in *GrantRequest, opts ...grpc.CallOption) (*GrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantResponse)
	err := c.cc.Invoke(ctx, GrantService_CreateGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrantServiceServer is the server API for GrantService service.
// All implementations must embed UnimplementedGrantServiceServer
// for forward compatibility.
type GrantServiceServer interface {
	CreateGrant(context.Context, *GrantRequest) (*GrantResponse, error)
	mustEmbedUnimplementedGrantServiceServer()
}

// UnimplementedGrantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrantServiceServer struct{}

func (UnimplementedGrantServiceServer) CreateGrant(context.Context, *GrantRequest) (*GrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGrant not implemented")
}
func (UnimplementedGrantServiceServer) mustEmbedUnimplementedGrantServiceServer() {}
func (UnimplementedGrantServiceServer) testEmbeddedByValue()                      {}

// UnsafeGrantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrantServiceServer will
// result in compilation errors.
type UnsafeGrantServiceServer interface {
	mustEmbedUnimplementedGrantServiceServer()
}

func RegisterGrantServiceServer(s grpc.ServiceRegistrar, srv GrantServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrantService_ServiceDesc, srv)
}

func _GrantService_CreateGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantServiceServer).CreateGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrantService_CreateGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantServiceServer).CreateGrant(ctx, req.(*GrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrantService_ServiceDesc is the grpc.ServiceDesc for GrantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grant.GrantService",
	HandlerType: (*GrantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGrant",
			Handler:    _GrantService_CreateGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/grant.proto",
}
