# Generated by Django 5.1.6 on 2025-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrantApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("abstract", models.TextField()),
                ("objectives", models.TextField()),
                ("research_question", models.TextField()),
                ("background", models.TextField()),
                ("plan", models.TextField()),
                ("dissemination", models.TextField()),
                ("cv", models.TextField()),
                ("budget", models.TextField()),
                ("budget_justification", models.TextField()),
                ("non_academic_dissemination", models.TextField()),
                ("project_management", models.TextField()),
                ("appendices", models.TextField()),
                ("ethics", models.TextField()),
                ("data_management_plan", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
